PR-1852 - all state models should be configurable
openlibraryenvironment/mod-rs pull request #746
Opened 2024-07-24 13:30 UTC by EddiTim

2024-07-24 13:40 UTC, jakub-id requested changes

2024-07-24 13:40 UTC, jakub-id commented on service/grails-app/services/org/olf/rs/statemodel/StatusService.groovy
> +            } else if (request.deliveryMethod?.value == 'url') {
This doesn't match the old logic and this branch will never execute. This condition should be under the`loan` condition. I would prefer you keeped the old logic as is:
```
if serviceType == copy {
    non-returnables
} else {
    if deliveryMethod == URL {
      digital-returnables
    } else {
       returnables
    }
}
```

2024-07-24 13:40 UTC, jakub-id commented on service/src/main/groovy/org/olf/rs/referenceData/SettingsData.groovy
> -    public static final String SETTING_STATE_MODEL_REQUESTER_CDL = 'state_model_requester_cdl';
Was this static used for anything?

2024-07-24 13:40 UTC, jakub-id commented on service/src/main/groovy/org/olf/rs/referenceData/SettingsData.groovy
> -    public static final String SETTING_STATE_MODEL_RESPONDER_CDL = 'state_model_responder_cdl';
Was this static used for anything?

2024-07-25 06:41 UTC, EddiTim commented on service/src/main/groovy/org/olf/rs/referenceData/SettingsData.groovy
> -    public static final String SETTING_STATE_MODEL_REQUESTER_CDL = 'state_model_requester_cdl';
No, I will remove it.

2024-07-25 06:41 UTC, EddiTim commented on service/src/main/groovy/org/olf/rs/referenceData/SettingsData.groovy
> -    public static final String SETTING_STATE_MODEL_RESPONDER_CDL = 'state_model_responder_cdl';
No, I will remove it.

2024-07-25 17:01 UTC, skomorokh commented
It seems like this change prevents `StatusService.getStateModel` from ever resolving to the CDL responder model (and has no setting for which model to use for CDL responder)

2024-07-26 06:59 UTC, EddiTim commented
> It seems like this change prevents `StatusService.getStateModel` from ever resolving to the CDL responder model (and has no setting for which model to use for CDL responder)

if (request.deliveryMethod?.value == 'url') {
                    settingsKey = isRequester
                            ? SettingsData.SETTING_STATE_MODEL_REQUESTER_DIGITAL_RETURNABLE
                            : SettingsData.SETTING_STATE_MODEL_RESPONDER_DIGITAL_RETURNABLE
                            
SETTING_STATE_MODEL_RESPONDER_DIGITAL_RETURNABLE = CDLResponder

2024-07-29 08:02 UTC, EddiTim commented
> There is no single responder model for digital returnable. There is a CDL responder and there will be an eBook responder. They're both digital returnables but they have a different workflow on the supplier side. It's entirely possible the same tenant will use both so it's not just that they can set it to one or the other.
> 
> Whereas on the requester side, at least as initially envisioned, they have the same process and we group them together as digital returnable requester.

@jakub-id Please have a look and we need to decide what to do, as Jason is pointing out a valid thing

2024-07-29 09:12 UTC, jakub-id commented
> There is no single responder model for digital returnable. There is a CDL responder and there will be an eBook responder. They're both digital returnables but they have a different workflow on the supplier side. It's entirely possible the same tenant will use both so it's not just that they can set it to one or the other.
> 
> Whereas on the requester side, at least as initially envisioned, they have the same process and we group them together as digital returnable requester.

I don't see that the old code supported two different digital returnables state models for the responder as it hard-coded the  CDL state model. I think we should go ahead and approve it as it allows configuring state models for ZFL and create a separate ticket for more granular configurability of the digital returnable state models.

2024-07-29 11:36 UTC, merged

2024-07-29 13:27 UTC, skomorokh commented
Please use the name `SETTING_STATE_MODEL_RESPONDER_CDL` instead of `SETTING_STATE_MODEL_RESPONDER_DIGITAL_RETURNABLE` so that we can avoid having to rename it when we implement ebooks.